title: NetAI Research Group
description: NetAI Research Group led by Dr. Omar Alhussein
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


# Just the Docs settings
just_the_docs:
  search_enabled: true
  show_localization: false
  aux_links: false
  # Set the order of navigation
  nav_order: 
    - Home
    - Team
    - Research
    - Publications
    - Patents

